spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reactive_crud
    username: postgres
    password: hello123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
